"""Python-side tests: bindings, QuantLib cross-checks and model round-trips (no market data)."""

import numpy as np
import pytest
import qpricing as qp
import QuantLib as ql
from qpricing.models import (
    AdHocBlackScholes,
    BlackScholes,
    Heston,
    Schrodinger,
    Slice,
    black76,
    reanchor,
)


def _ql_black(is_call, F, K, T, sigma, df):
    opt = ql.Option.Call if is_call else ql.Option.Put
    return ql.blackFormula(opt, K, F, sigma * np.sqrt(T), df)


@pytest.mark.parametrize("is_call", [True, False])
def test_black76_matches_quantlib(is_call):
    F, T, df = 3577.0, 9 / 365, 0.999
    for K in (3000.0, 3400.0, 3577.0, 3700.0, 3900.0):
        for sigma in (0.15, 0.4, 0.9):
            ref = _ql_black(is_call, F, K, T, sigma, df)
            got = qp.black76_price(is_call, F, K, T, sigma, df)
            assert got == pytest.approx(ref, rel=1e-10, abs=1e-12)
            assert black76(np.array([is_call]), F, np.array([K]), T, sigma, df)[0] == pytest.approx(
                ref, rel=1e-10, abs=1e-12)


def test_flat_well_is_black_scholes():
    F, T, df = 3600.0, 14 / 365, 0.998
    strikes = np.array([3200.0, 3450.0, 3600.0, 3750.0, 3950.0])
    is_call = strikes >= F
    got = qp.schrodinger_price(qp.EffectiveVolParams.constant(0.3), F, T, df, strikes, is_call)
    ref = [_ql_black(c, F, K, T, 0.3, df) for c, K in zip(is_call, strikes, strict=True)]
    np.testing.assert_allclose(got, ref, atol=5e-3)


def test_solve_diagnostics():
    sol = qp.solve(qp.EffectiveVolParams(0.012, 0.45, -0.8, 0.02, 0.05), 9 / 365, qp.GridSpec(), 3)
    assert sol["mass"] == pytest.approx(1.0, abs=1e-5)
    assert sol["forward_ratio"] == pytest.approx(1.0, abs=1e-5)
    assert np.all(np.diff(sol["energies"]) > 0)


def _synthetic_slice(model, params, days=10):
    """A slice whose 'market' prices are generated by `model` itself."""
    F, S, r = 3600.0, 3595.0, 0.03
    T = days / 365
    strikes = np.arange(3150.0, 3950.0, 25.0)
    is_call = strikes >= F
    s = Slice(F, S, T, days, r, np.exp(-r * T), strikes, is_call, np.zeros_like(strikes))
    s.mid = model.price(params, s)
    return s


@pytest.mark.parametrize(
    "model, truth",
    [
        (BlackScholes(), np.array([0.27])),
        (AdHocBlackScholes(), np.array([0.25, -1.2, 4.0])),
        (Schrodinger(), np.array([0.03, 1.5, -0.6, 0.02, 0.04])),
    ],
)
def test_calibration_recovers_its_own_prices(model, truth):
    s = _synthetic_slice(model, truth)
    fitted = model.calibrate(s)
    assert np.max(np.abs(model.price(fitted, s) - s.mid)) < 0.02


def test_heston_round_trip_through_quantlib():
    model = Heston()
    truth = np.array([0.06, 3.0, 2.0, -0.75, 0.04])  # theta, kappa, sigma, rho, v0
    s = _synthetic_slice(model, truth, days=21)
    fitted = model.calibrate(s)
    assert np.max(np.abs(model.price(fitted, s) - s.mid)) < 0.05


def test_reanchor_recovers_a_level_shift():
    m = Schrodinger()
    base = np.array([0.03, 1.5, -0.6, 0.02, 0.04])
    s = _synthetic_slice(m, m.with_level(base, 1.2))
    anchor = np.argsort(np.abs(s.k))[:2]
    mask = np.zeros(len(s.strikes), dtype=bool)
    mask[anchor] = True
    fitted = reanchor(m, base, s, mask)
    np.testing.assert_allclose(fitted, m.with_level(base, 1.2), rtol=1e-3)
